### ISSUE TITLE
Need of a license or permission to use code for commercial purposes

### ISSUE THREAD

**Issue by yurigba** [dataengineerone/de1-python#1]
Hi,

I found the work in this repo very useful, but it doesn't specify how it can be used for proprietary code. There is a need to explicitly define these (see [here](https://softwareengineering.stackexchange.com/a/276147)) or permission from the author to use it.

**Comment by dataengineerone** [comment]
Great catch, thanks @yurigba . I've added an MIT license; please enjoy!
